import { Card } from './cards.types';

const cards: Array<Card> = [
  { suit: 'D', value: 1, background: require('./imgs/AD.png') },
  { suit: 'D', value: 2, background: require('./imgs/2D.png') },
  { suit: 'D', value: 3, background: require('./imgs/3D.png') },
  { suit: 'D', value: 4, background: require('./imgs/4D.png') },
  { suit: 'D', value: 5, background: require('./imgs/5D.png') },
  { suit: 'D', value: 6, background: require('./imgs/6D.png') },
  { suit: 'D', value: 7, background: require('./imgs/7D.png') },
  { suit: 'D', value: 8, background: require('./imgs/8D.png') },
  { suit: 'D', value: 9, background: require('./imgs/9D.png') },
  { suit: 'D', value: 10, background: require('./imgs/10D.png') },
  { suit: 'D', value: 11, background: require('./imgs/JD.png') },
  { suit: 'D', value: 12, background: require('./imgs/QD.png') },
  { suit: 'D', value: 13, background: require('./imgs/KD.png') },
  { suit: 'C', value: 1, background: require('./imgs/AC.png') },
  { suit: 'C', value: 2, background: require('./imgs/2C.png') },
  { suit: 'C', value: 3, background: require('./imgs/3C.png') },
  { suit: 'C', value: 4, background: require('./imgs/4C.png') },
  { suit: 'C', value: 5, background: require('./imgs/5C.png') },
  { suit: 'C', value: 6, background: require('./imgs/6C.png') },
  { suit: 'C', value: 7, background: require('./imgs/7C.png') },
  { suit: 'C', value: 8, background: require('./imgs/8C.png') },
  { suit: 'C', value: 9, background: require('./imgs/9C.png') },
  { suit: 'C', value: 10, background: require('./imgs/10C.png') },
  { suit: 'C', value: 11, background: require('./imgs/JC.png') },
  { suit: 'C', value: 12, background: require('./imgs/QC.png') },
  { suit: 'C', value: 13, background: require('./imgs/KC.png') },
  { suit: 'H', value: 1, background: require('./imgs/AH.png') },
  { suit: 'H', value: 2, background: require('./imgs/2H.png') },
  { suit: 'H', value: 3, background: require('./imgs/3H.png') },
  { suit: 'H', value: 4, background: require('./imgs/4H.png') },
  { suit: 'H', value: 5, background: require('./imgs/5H.png') },
  { suit: 'H', value: 6, background: require('./imgs/6H.png') },
  { suit: 'H', value: 7, background: require('./imgs/7H.png') },
  { suit: 'H', value: 8, background: require('./imgs/8H.png') },
  { suit: 'H', value: 9, background: require('./imgs/9H.png') },
  { suit: 'H', value: 10, background: require('./imgs/10H.png') },
  { suit: 'H', value: 11, background: require('./imgs/JH.png') },
  { suit: 'H', value: 12, background: require('./imgs/QH.png') },
  { suit: 'H', value: 13, background: require('./imgs/KH.png') },
  { suit: 'S', value: 1, background: require('./imgs/AS.png') },
  { suit: 'S', value: 2, background: require('./imgs/2S.png') },
  { suit: 'S', value: 3, background: require('./imgs/3S.png') },
  { suit: 'S', value: 4, background: require('./imgs/4S.png') },
  { suit: 'S', value: 5, background: require('./imgs/5S.png') },
  { suit: 'S', value: 6, background: require('./imgs/6S.png') },
  { suit: 'S', value: 7, background: require('./imgs/7S.png') },
  { suit: 'S', value: 8, background: require('./imgs/8S.png') },
  { suit: 'S', value: 9, background: require('./imgs/9S.png') },
  { suit: 'S', value: 10, background: require('./imgs/10S.png') },
  { suit: 'S', value: 11, background: require('./imgs/JS.png') },
  { suit: 'S', value: 12, background: require('./imgs/QS.png') },
  { suit: 'S', value: 13, background: require('./imgs/KS.png') },
];

export default cards;

export const back: Card = {
  suit: '',
  value: NaN,
  background: require('./imgs/_blue_back.png'),
};
